Added a few more modifications. The changes to bashrc and company have been made. Still have a bit to go on applying manual patches.

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -15,7 +15,29 @@ wmakeCheckPwd "$WM_PROJECT_DIR" || {
 }
 
 # wmake is required for subsequent targets
-( cd wmake/src && make )
+if ! isMinGW; then
+
+  ( cd wmake/src && make )
+
+else
+
+  if [ -d "wmake/bin/$WM_ARCH$WM_COMPILER" ]; then
+    filecount=`ls -1A "wmake/bin/$WM_ARCH$WM_COMPILER" | wc -l`
+  fi
+
+  if [ "$filecount" = "0" -o ! -d "wmake/bin/$WM_ARCH$WM_COMPILER" ]; then
+    ( cd wmake/src && make cc="gcc" )
+  fi
+  filecount=`ls -1A "wmake/bin/$WM_ARCH$WM_COMPILER" | wc -l`
+
+  #use the wmake compiled for linux usage, if not built with system's gcc
+  if [ "$filecount" = "0" -o ! -d "wmake/bin/$WM_ARCH$WM_COMPILER" ]; then
+    echo "Aborting Allwmake, because a working wmake wasn't found nor built."
+    exit 1
+  fi
+  unset filecount
+
+fi
 
 # build ThirdParty sources
 if [ -d "$WM_THIRD_PARTY_DIR" ]
