Had to add search functions for looking for the correct mpirun or mpiexec to be used in RunParallel.

diff --git a/bin/tools/RunFunctions b/bin/tools/RunFunctions
--- a/bin/tools/RunFunctions
+++ b/bin/tools/RunFunctions
@@ -73,16 +73,17 @@ runParallel()
 
       if [ -z "$MPI_OVERRIDE_RUN_PARALLEL" ]
       then
-        
+
+        export mpirun=`findMpirun` || echo "'mpirun' not found"
         load_mpi_opts
 
         #if [ "$WM_SCHEDULER" ]
         #then
         #    echo "$PWD: $WM_SCHEDULER -np $nProcs" 1>&2
-        #    $WM_SCHEDULER -np $nProcs "( mpirun -np $nProcs $APP_RUN -parallel $* < /dev/null > log.$APP_NAME 2>&1 )"
+        #    $WM_SCHEDULER -np $nProcs "( $mpirun -np $nProcs $APP_RUN -parallel $* < /dev/null > log.$APP_NAME 2>&1 )"
         #else
 
-            ( mpirun -np $nProcs $mpiopts $APP_RUN -parallel $* < /dev/null > log.$APP_NAME 2>&1 )
+            ( $mpirun -np $nProcs $mpiopts $APP_RUN -parallel $* < /dev/null > log.$APP_NAME 2>&1 )
         #fi
 
       else
@@ -173,7 +174,8 @@ runParallel ()
 
           load_mpi_opts
 
-          mpirun -np $nProcs $mpiopts $APP_RUN -parallel $* < /dev/null > log.$APP_NAME 2>&1  &
+          export mpirun=`findMpirun` || echo "'mpirun' not found"
+          $mpirun -np $nProcs $mpiopts $APP_RUN -parallel $* < /dev/null > log.$APP_NAME 2>&1  &
 
         else
 
@@ -322,6 +324,67 @@ sedIt()
   else
     sed -i -e "$1" $2
   fi
+}
+
+#Functions bellow this line were copied from foamJob --------------------------
+
+# replacement for possibly buggy 'which'
+findExec() {
+    case "$1" in
+    */*)
+        if [ -x "$1" ]
+        then
+            echo "$1"
+            return 0
+        fi
+        ;;
+    esac
+
+    oldIFS=$IFS
+    IFS=':'
+    for d in $PATH
+    do
+        # echo "testing: $d/$1" 1>&2
+        if [ -x "$d/$1" -a ! -d "$d/$1" ]
+        then
+            # echo "Found exec: $d/$1" 1>&2
+            IFS=$oldIFS
+            echo "$d/$1"
+            return 0
+        fi
+     done
+     IFS=$oldIFS
+     echo ""
+     return 1
+}
+
+#find mpirun or mpiexec, by checking if MPI_ARCH_PATH matches the path for each
+findMpirun() {
+  path2mpirun=`findExec mpirun`
+  path2mpiexec=`findExec mpiexec`
+
+  if [ -n "$path2mpirun" -a "${path2mpirun%/*}" = "$MPI_ARCH_PATH/bin" ]; then
+    echo $path2mpirun
+    return 0
+  fi
+
+  if [ -n "$path2mpiexec" -a "${path2mpiexec%/*}" = "$MPI_ARCH_PATH/bin" ]; then
+    echo $path2mpiexec
+    return 0
+  fi
+
+  if [ -n "$path2mpirun" ]; then
+    echo $path2mpirun
+    return 0
+  fi
+
+  if [ -n "$path2mpiexec" ]; then
+    echo $path2mpiexec
+    return 0
+  fi
+
+  echo ""
+  return 1
 }
 
 #------------------------------------------------------------------------------
